-- View to find total, min, max, avg sal
CREATE VIEW AGGREGATE_VIEW (MAXIMUM_SAL, MINIMUM_SAL, AVERAGE_SAL, TOTAL_SAL) AS
SELECT MAX(SAL), MIN(SAL), ROUND(AVG(SAL), 4), SUM(SAL)
FROM EMP;

SELECT *
FROM AGGREGATE_VIEW;

DROP VIEW EMPDATA_VIEW;

-- View displays deptno, deptname, enum and ename
CREATE VIEW EMPDATA_VIEW (DEPT_NUM, DEPT_NAME, EMP_NUM, EMP_NAME) AS
SELECT D.DEPTNO, DNAME, EMPNO, ENAME
FROM DEPT D,
     EMP E
WHERE D.DEPTNO = E.DEPTNO;

SELECT *
FROM EMPDATA_VIEW;

-- Create a view which displays the names of all employees working in deptno. 13.
CREATE VIEW EMP_VIEW (EMP_NAME, DEPT_NUM) AS
SELECT ENAME, DEPTNO
FROM EMP
WHERE DEPTNO = 30
WITH CHECK OPTION;

DROP VIEW EMP_VIEW;

SELECT *
FROM EMP_VIEW;

UPDATE EMP_VIEW
SET EMP_VIEW.DEPT_NUM = 80
WHERE EMP_VIEW.DEPT_NUM = 30;

-- Create a view which should display details of all clerks present in emp table. (with check option view)
CREATE VIEW CLERK_VIEW
AS
SELECT *
FROM EMP
WHERE JOB = 'CLERK'
WITH CHECK OPTION;

SELECT *
FROM CAT
WHERE TABLE_TYPE = 'VIEW';

CREATE VIEW TEST_VIEW_RO AS
SELECT *
FROM EMP;

SELECT *
FROM TEST_VIEW_RO;