DECLARE
    V_EMP_ID       NUMBER;
    V_EMP_NAME     VARCHAR2(20);
    V_EMP_DEPT_NUM NUMBER;
    V_EMP_SAL      NUMBER;
    V_EMP_COMM     NUMBER;
BEGIN
    SELECT EMPNO, ENAME, DEPTNO, SAL, COMM
    INTO V_EMP_ID, V_EMP_NAME, V_EMP_DEPT_NUM, V_EMP_SAL, V_EMP_COMM
    FROM EMP
    WHERE SAL = (SELECT MAX(SAL) FROM EMP);

    DBMS_OUTPUT.PUT_LINE('EMPLOYEE ID : ' || V_EMP_ID);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME : ' || V_EMP_NAME);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE DEPARTMENT NO. : ' || V_EMP_DEPT_NUM);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE SALARY : ' || V_EMP_SAL);
    DBMS_OUTPUT.PUT_LINE('TOTAL EMPLOYEE SALARY : ' || V_EMP_SAL + V_EMP_COMM);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO EMPLOYEE FOUND WITH ID : ' || V_EMP_ID);
END;