SELECT *
FROM COURSE;

SELECT *
FROM PARTICIPANT;

SELECT *
FROM DEPT;

SELECT *
FROM EMP;

SELECT *
FROM DEPT D
         JOIN EMP E on D.DEPTNO = E.DEPTNO;

SELECT ENAME "EMPLOYEE NAME", ROUND(MONTHS_BETWEEN(SYSDATE, HIREDATE) / 12) "EXPERIENCE"
FROM EMP;

SELECT *
FROM EMP,
     DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

SELECT ENAME "EMPLOYEE NAME", JOB "EMPLOYEE JOB"
FROM EMP
WHERE JOB IN ('SALESMAN', 'MANAGER');

SELECT EMPNO, ENAME, JOB, SAL
FROM EMP E1
WHERE 1 = (SELECT COUNT(DISTINCT SAL)
           FROM EMP E2
           WHERE E2.SAL > E1.SAL);