CREATE TABLE PARTICIPANT
(
    PID    NUMBER(4)    NOT NULL,
    PNAME  VARCHAR2(25) NOT NULL,
    GENDER CHAR(1)      NOT NULL,
    CID    NUMBER(3),
    CONSTRAINT PARTICIPANT_PK_PID PRIMARY KEY (PID),
    CONSTRAINT PARTICIPANT_CK_PID CHECK (PID BETWEEN 1001 AND 9999),
    CONSTRAINT PARTICIPANT_CK_GENDER CHECK (GENDER IN ('M', 'F')),
    CONSTRAINT PARTICIPANT_FK_COURSE_CID FOREIGN KEY
        (CID) REFERENCES COURSE (CID)
);