-- VIEW ALL OBJECTS FROM CURRENT TABLESPACE
SELECT *
FROM TAB;

-- ALL FEMALES IN PARTICIPANT TABLE
SELECT *
FROM PARTICIPANT
WHERE GENDER = 'F';

-- ALL FEMALES ORDER BY CID
SELECT *
FROM PARTICIPANT
WHERE GENDER = 'F'
ORDER BY CID;

-- ALL FEMALES ORDER BY CID IN DESCENDING
SELECT *
FROM PARTICIPANT
WHERE GENDER = 'F'
ORDER BY CID DESC;

-- QUERYING CERTAIN COLUMNS
SELECT PNAME, PID
FROM PARTICIPANT;

-- QUERYING CERTAIN COLUMNS WITH ALIASES
SELECT PNAME AS "PARTICIPANT", PID AS ID
FROM PARTICIPANT;

-- QUERYING CERTAIN COLUMNS WITH ALIASES
SELECT PNAME "PARTICIPANT", PID "ID"
FROM PARTICIPANT;