-- 1. DISPLAY DETAILS OF EVERY MALE PARTICIPANT.
SELECT *
FROM PARTICIPANT
WHERE GENDER = 'M';

-- 2. DISPLAY DETAILS OF EVERY MALE PARTICIPANT IN THE INCREASING ORDER OF THEIR COURSE ID.
SELECT *
FROM PARTICIPANT
WHERE GENDER = 'M'
ORDER BY CID ASC;

-- 3. DISPLAY THE DETAILS OF THOSE PARTICIPANTS WHOSE COURSE ID IS NULL.
SELECT *
FROM PARTICIPANT
WHERE CID IS NULL;

-- 4. DISPLAY DETAILS OF THOSE PARTICIPANTS WHOSE COURSE ID IN NOT NULL.
SELECT *
FROM PARTICIPANT
WHERE CID IS NOT NULL;

-- 5. DISPLAY DETAILS OF THOSE COURSES WHOSE CREDIT IS GREATER THAN 3.
SELECT CID "COURSE ID", CNAME "COURSE NAME", CREDIT
FROM COURSE
WHERE CREDIT > 3;

-- 6. DISPLAY DETAILS OF THOSE COURSES WHOSE NAME STARTS WITH LETTER D.
SELECT CID "COURSE ID", CNAME "COURSE NAME", CREDIT
FROM COURSE
WHERE CNAME LIKE 'D%';

-- 7. DISPLAY DETAILS OF THOSE COURSES WHOSE NAME'S SECOND LETTER IS A.
SELECT CID "COURSE ID", CNAME "COURSE NAME", CREDIT
FROM COURSE
WHERE CNAME LIKE '_A%';

-- 8. DISPLAY CID, CNAME, PID, PNAME OF ALL PARTICIPANTS WHO ENROLLED IN DBMS COURSE.
SELECT PID "ID", PNAME "PARTICIPANT NAME", C.CNAME, C.CID
FROM COURSE C
         JOIN PARTICIPANT P ON C.CID = P.CID
WHERE CNAME = 'DBMS';