CREATE USER shantanu IDENTIFIED BY mane;

ALTER USER shantanu IDENTIFIED BY mane2;

GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO shantanu;

-- Unlock user
-- ALTER USER SCOTT IDENTIFIED BY TIGER ACCOUNT UNLOCK;

CREATE PROFILE DB_USER_PROFILE LIMIT FAILED_LOGIN_ATTEMPTS 3;

-- connect system/shan;

ALTER PROFILE DB_USER_PROFILE
    LIMIT PASSWORD_REUSE_MAX 5
    PASSWORD_REUSE_TIME UNLIMITED;

-- CONNECT shantanu/mane2;

SELECT *
FROM EMP;

-- CONNECT SYSTEM/SHAN;

GRANT ALL ON SCOTT.EMP TO shantanu;
GRANT ALL ON SCOTT.DEPT TO shantanu;


-- CONNECT shantanu/mane2;

SELECT *
FROM EMP;