-- Run query and store value in variable

DECLARE
    V_EMP_NAME VARCHAR2(20);
    V_EMP_JOB  VARCHAR2(20);
    V_EMP_SAL  NUMBER;
    V_EMP_NUM  NUMBER := 7839;
BEGIN
    SELECT ENAME, JOB, SAL
    INTO V_EMP_NAME, V_EMP_JOB, V_EMP_SAL
    FROM EMP
    WHERE EMPNO = V_EMP_NUM;

    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME : ' || V_EMP_NAME);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE JOB : ' || V_EMP_JOB);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE SAL : ' || V_EMP_SAL);
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE ID : ' || V_EMP_NUM);
END;