SELECT *
FROM SAILORS;

SELECT *
FROM BOATS;

SELECT *
FROM RESERVES;

SELECT COUNT(BID)
FROM BOATS;

SELECT SID, BID
FROM RESERVES;

SELECT RATING, COUNT(SNAME) "NUMBER OF SAILORS"
FROM SAILORS
GROUP BY RATING;

SELECT R.SID, SNAME, COUNT(BID)
FROM RESERVES R
         JOIN SAILORS S ON R.SID = S.SID
GROUP BY R.SID, SNAME;


SELECT S.SID
FROM SAILORS S
WHERE EXISTS(
              SELECT BID
              FROM RESERVES R
              WHERE S.SID = R.SID
                AND R.BID = 103);

SELECT *
FROM RESERVES R
         JOIN SAILORS S ON R.SID = S.SID
WHERE BID = 103;

SELECT BID, COUNT(BID)
FROM RESERVES
GROUP BY BID
HAVING BID IN (SELECT BID
               FROM BOATS
               WHERE COLOR = 'red');

