-- Q3. Create a function that takes deptno as argument and return the name of the department. (scott/tiger)

CREATE OR REPLACE FUNCTION RET_DEPT_NAME(DEPT_NUM IN NUMBER)
    RETURN DEPT.DNAME%TYPE
AS
    V_DEPT_NAME DEPT.DNAME%TYPE;
BEGIN
    SELECT DNAME INTO V_DEPT_NAME FROM DEPT WHERE DEPTNO = DEPT_NUM;

    RETURN V_DEPT_NAME;

END RET_DEPT_NAME;

DECLARE
    DEPT_NUM  NUMBER := &DEPT_NUM;
    DEPT_NAME DEPT.DNAME%TYPE;
BEGIN
    DEPT_NAME := RET_DEPT_NAME(10);

    DBMS_OUTPUT.PUT_LINE('DEPT NO. : ' || DEPT_NUM || ', DEPT NAME : ' || DEPT_NAME);
END;