-- CREATE A SYNONYM FOR A TABLE.
-- CREATE SYNONYM S1 FOR EMP;

-- SELECT *
-- FROM S1;

-- CREATE SYNONYM S2 FOR DEPT;

-- DROP SEQUENCE S1;

-- CREATE A PUBLIC SYNONYM OF DEPARTMENTS TABLE IN HR SCHEMA.
-- CREATE PUBLIC SYNONYM DEPT_SYN FOR HR.;

CREATE PUBLIC SYNONYM SP FOR DEPT;

SELECT *
FROM SP;

DESCRIBE S1;