-- USING CONCAT OPERATOR, ||
SELECT PNAME || ' takes course in ' || CNAME || ' of ' || CREDIT || ' credits.'
FROM COURSE C
         JOIN PARTICIPANT P
              ON C.CID = P.CID;


-- CROSS JOIN ON COURSE AND PARTICIPANT
SELECT *
FROM PARTICIPANT
         CROSS JOIN COURSE;

-- CROSS JOIN WITHOUT KEYWORD
SELECT *
FROM PARTICIPANT,
     COURSE;

-- EQUI JOIN ON COURSE AND PARTICIPANT TABLES
SELECT *
FROM PARTICIPANT P
         JOIN
     COURSE C ON P.CID = C.CID;

-- EQUI JOIN ON COURSE AND PARTICIPANT TABLES WITHOUT KEYWORDS
SELECT *
FROM PARTICIPANT P,
     COURSE C
WHERE C.CID = P.CID;

-- NATURAL JOIN ON COURSE AND PARTICIPANT
SELECT *
FROM PARTICIPANT
         NATURAL JOIN
     COURSE;