-- LEFT OUTER JOIN ON COURSE AND PARTICIPANT
SELECT *
FROM PARTICIPANT P
         LEFT OUTER JOIN COURSE C on P.CID = C.CID;

-- LEFT OUTER JOIN ON COURSE AND PARTICIPANT WITHOUT KEYWORDS
SELECT *
FROM PARTICIPANT P,
     COURSE C
WHERE P.CID = C.CID (+);

-- RIGHT OUTER JOIN ON COURSE AND PARTICIPANT
SELECT *
FROM PARTICIPANT P
         RIGHT OUTER JOIN COURSE C on P.CID = C.CID
ORDER BY P.PID;

-- RIGHT OUTER JOIN ON COURSE AND PARTICIPANT WITHOUT KEYWORDS
SELECT *
FROM PARTICIPANT P,
     COURSE C
WHERE P.CID (+) = C.CID;

-- FULL OUTER JOIN ON COURSE AND PARTICIPANT
SELECT *
FROM PARTICIPANT P
         FULL OUTER JOIN COURSE C on P.CID = C.CID;

-- FULL OUTER JOIN ON COURSE AND PARTICIPANT WITHOUT KEYWORDS
SELECT *
FROM PARTICIPANT P,
     COURSE C
WHERE P.CID (+) = C.CID (+); -- ! WILL GIVE ERROR
