SELECT *
FROM PARTICIPANT;

SELECT *
FROM COURSE;

SELECT COUNT(CID) "NO OF NON NULL ROWS"
FROM PARTICIPANT;

SELECT CNAME, PNAME
FROM COURSE C,
     PARTICIPANT P
WHERE C.CID = P.CID
GROUP BY CNAME, PNAME;

DELETE
FROM PARTICIPANT
WHERE PNAME = 'CHERRY';

SELECT CID, COUNT(*)
FROM PARTICIPANT
GROUP BY CID
HAVING COUNT(*) > 3;

DROP TABLE COURSE PURGE;

DELETE
FROM COURSE
WHERE CID = 103;

ALTER TABLE PARTICIPANT
    DROP CONSTRAINT PARTICIPANT_FK_COURSE_CID;

ALTER TABLE PARTICIPANT
    ADD CONSTRAINT PARTICIPANT_FK_COURSE_CID
        FOREIGN KEY (CID) REFERENCES COURSE (CID)
            ON DELETE SET NULL;


SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, DELETE_RULE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'PARTICIPANT';

DELETE
FROM course
WHERE cid = 102;

ROLLBACK;





