-- UNION OPERATIONS ON PARTICIPANT_1 AND PARTICIPANT_2
    (SELECT * FROM PARTICIPANT_1)
    UNION
    (SELECT * FROM PARTICIPANT_2);

-- INTERSECT OPERATIONS ON PARTICIPANT_1 AND PARTICIPANT_2
    (SELECT * FROM PARTICIPANT_1)
    INTERSECT
    (SELECT * FROM PARTICIPANT_2);

-- DIFFERENCE OPERATIONS ON PARTICIPANT_1 AND PARTICIPANT_2
    (SELECT * FROM PARTICIPANT_1)
    MINUS
    (SELECT * FROM PARTICIPANT_2);

-- INTERSECT OPERATIONS ON PARTICIPANT_1 AND PARTICIPANT_2 USING DIFFERENCE
SELECT *
FROM PARTICIPANT_1
MINUS
((SELECT * FROM PARTICIPANT_1)
 MINUS
 (SELECT * FROM PARTICIPANT_2));