-- GIVEN COURSE IDS FROM COURSE TABLE
SELECT *
FROM COURSE;

-- REMOVE EVERY TUPLE FROM COURSE TABLE
DELETE
FROM COURSE;

SELECT *
FROM COURSE;

-- CREATE SEQUENCE FOR COURSE
CREATE SEQUENCE COURSE_SQ
    INCREMENT BY 1
    MINVALUE 101
    MAXVALUE 107;

SELECT *
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'COURSE_SQ';

SELECT *
FROM CAT;

INSERT INTO COURSE
VALUES (COURSE_SQ.NEXTVAL, 'MAT', 2);

SELECT COURSE_SQ.currval
FROM DUAL;

INSERT INTO COURSE
VALUES (COURSE_SQ.NEXTVAL, 'ML', 4);

INSERT INTO COURSE
VALUES (COURSE_SQ.NEXTVAL, 'DBMS', 3);

INSERT INTO COURSE
VALUES (COURSE_SQ.NEXTVAL, 'OOP', 2);

-- ALTER SEQUENCE COURSE_SQ START WITH 108; ERROR DEGA PAJJI

